### ISSUE TITLE
Post-It / Tag feature

### ISSUE THREAD

**Issue by SolidNerd** [ssddanbrown/BookStack#104]
Hey, 
i would like to know what are you thinking of my idea. I would like to tag pages with special names like 'shakespeer' or 'needtoknow'. After that I would like to be able to search of it directly in the global search with a pre character like  ':needtoknow' or something else. The result should be all pages with this tag now.

**Comment by ssddanbrown** [comment]
Hi @SolidNerd,
Thanks for the suggestion. This is absolutely something I want to be able to do in BookStack and an extra dimension of organisation is requested by many at the moment. This is proposed in #48 and the advanced searching is open in #64. Since this is a combination of the two mentioned issues I will close this one.

I've marked the attribute system (Which will act like tags) to [be in the next release](https://github.com/ssddanbrown/BookStack/milestones?state=open) and the search will follow later once the attribute system is stable.
