### ISSUE TITLE
Support Custom Authentication

### ISSUE THREAD

**Issue by joshlewis** [ssddanbrown/BookStack#109]
I'd like to integrate BookStack into an existing Laravel app that has its own authentication system already built. (It's Laravel's built-in concept of Users, but that may or may not matter. Not sure.) So really, I just want this wiki to be on a collection of routes within a larger app, and use the exact same login page and same logins that the rest of the app already uses.

Two questions:

1. Is that functionality possible to hack in today without changing BookStack?
2. Would changing BookStack in some way make the process easier for future developers to integrate with custom authentication?
3. If the external system also already has a concept of roles, perhaps there could be some way to integrate BookStack's custom roles with the custom roles that are outside the BookStack system?

Also, maybe implementing this could help #75 along?

**Comment by joshlewis** [comment]
Maybe what I'm really asking is if BookStack could support being installed _into an existing Laravel app_ with a `composer require` statement, providing wiki services to a larger app, and requiring that larger app to handle authentication (and other services?) on BookStack's behalf.

**Comment by ssddanbrown** [comment]
Hi @joshlewis, Sorry for my late reply. Answers to your questions:

1. No, There's a lot tied into the BookStack user system already such as the permissions system.
2. Possibly, I'm happy to support authentication standards and I'd like to have an API layer in the future which would help all areas of hackery.
3. Yeah, There could be although I'd like this to be based on a standard, The linked issue for matching up LDAP groups/roles with likely be very specific to LDAP.

I'm doubtful that BookStack could be `composer require`'d into another application in the future. The use cases for something like this would likely not be worth the extra amount of work it would take to 'modularise' everything since that different parts of BookStack are very much tied together tightly at the moment.

Sorry these aren't the answers you likely hoped for.

**Comment by joshlewis** [comment]
Got it. Thank you for the answer nonetheless!
