### ISSUE TITLE
Feature Request: Add Sorting to the Users Page

### ISSUE THREAD

**Issue by cpressland** [ssddanbrown/BookStack#113]
Hi,

It would be helpful to be able to sort the Settings > Users page by the other columns, specifically the roles column.

Thanks,
Chris Pressland

**Comment by ssddanbrown** [comment]
@cpressland Agreed, A simple search box would be ideal aswell. Marking for next release.

**Comment by ssddanbrown** [comment]
I've done the main thing of implementing sorting, ordering and searching. Unfortunately I could not find a good way to sort by roles since they are on a one-to-many relationship.

I have tried to make finding users by role more convenient by now linking the roles in that list to the actual role details page which, as of v0.9, displays a list of users.

I'll close this for now with the above changes but if doing what you require is still too much hassle let me know and I'll re-open this to discussion/ideas for implementing sorting.
