### ISSUE TITLE
"Save Page" redirects to "Page not found"

### ISSUE THREAD

**Issue by sk-webtronix** [ssddanbrown/BookStack#120]
Cannot save a new page, because it always redirects to "Page not Found". 

This error occurs, when you create a book and add a page without adding a Chapter.

It works, wenn you add a Book, a New Chapter and then a new page.

**Comment by ssddanbrown** [comment]
Hi @sk-webtronix,
Unfortunately I cannot replicate this issue. Could you tell me a little more about your setup?

- Are there permissions set on the Book?
- Can you do the action as an admin user?
- Did you upgrade from an earlier BookStack installation or is it fresh?

**Comment by sk-webtronix** [comment]
Hi @ssddanbrown,

sorry for the late reply. 
I haven't set any permissions. It is a complete clean installation. I'm logged in as an admin user. I have created a small screencast: http://screencast.com/t/zOYvPUKePH

**Comment by Fautzi** [comment]
Exactly same problem here, after clean installation. No errors in apache2 log or nginx.

**Comment by ssddanbrown** [comment]
@sk-webtronix Thanks for the screencast and @Fautzi Thanks for confirming you also have the issue.
I'm really sorry both of you are experiencing this issue.

Unfortunately I still cannot replicate this issue, Even with a fresh instance with a fresh DB. Would either of you be able to share your server stack? Just want to know the below so I can try to replicate the same environment:

- OS
- Database used (MySQL or MariaDB) & Version
- PHP version
- Apache or Nginx or something else?

**Comment by Fautzi** [comment]
- Debian 8
- MySQL 5.6
- PHP 5.6.20
- Apache2 and Nginx (as proxy)

Here https://kb.nynex.cz you can try it
login: test@test.com
password: test12345

**Comment by nwalke** [comment]
@ssddanbrown This is exactly the same PHP version issue I was having.

@Fautzi Can you try using PHP 7?

**Comment by Fautzi** [comment]
@nwalke 
Unfortunately no, i don't have any server with PHP 7

**Comment by nwalke** [comment]
I can try to find the line that was giving me problems, but this sounds
exactly the same.
On May 31, 2016 11:55 PM, "Fautzi" <notifications@github.com> wrote:

@nwalke <https://github.com/nwalke>
Unfortunately no, i don't have any server with PHP 7

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/ssddanbrown/BookStack/issues/120#issuecomment-222892496>,
or mute the thread
<https://github.com/notifications/unsubscribe/ABiu1D7x5h2RZ-8I3ELrHdL8jMUpbnUuks5qHRCvgaJpZM4IokGy>
.

**Comment by sk-webtronix** [comment]
Sorry, for the late reply. My configuration:
- Ubuntu 14.04.4
- PHP 5.5.9
- MySQL 5.6.30
- Apache2 2.4.7

**Comment by ssddanbrown** [comment]
After playing around in some Vagrant virtual machines I think I've found exactly when the issue occurs. It seems to only happen when using the php `mysql` driver (Installed via `php5-mysql`). When using the `mysqlnd` driver  (Installed via `apt-get install php5-mysqlnd` on ubuntu) this does not occur.

Try changing the mysql driver version, and remember to restart your webserver/php after changing it, to see if this fixes the problem.

I would still like to find why this happens but, from what I've seen, `mysqlnd` is usually superior and recommended over the `mysql` extension.

**Comment by Fautzi** [comment]
Thanks, that really help, but i think on many server is installed php5-mysql, what is the concrete issue with this? Driver is outdated? I found that native driver is more optimized and it's faster, but then why is php5-mysql installed by default?
Also thank you for your work and great piece of software

**Comment by ssddanbrown** [comment]
@Fautzi I'm not really sure, I think `php5-mysql` is in a lot of repos for legacy support. In PHP itself `mysqlnd` has been default since 5.4 (When compiling from source). I think the simpler name may lead many to thinking `mysql` is better to use than `mysqlnd`. I see it a lot in tutorials and it's not clear to those who don't know the differences.

Looking at the the [php7.0-mysql page](https://packages.debian.org/sid/php7.0-mysql) for Debian sid the mysql client is not a dependancy and `php7.0-mysqlnd` is a virtual package pointing to `php7.0-mysql` so I'm pretty sure that the `php7.0-mysql` packge in Debian sid (And therefore new Ubuntu releases) will just install `mysqlnd` as default.
