### ISSUE TITLE
add `unauthenticated` special role for unauthenticated users

### ISSUE THREAD

**Issue by squiddle** [ssddanbrown/BookStack#138]
That would allow to configure individual books to be publicly viewable or even editable (not sure about drafts, as there is no real user identity and garbage drafts could accumulate). But at least view should be selectable to allow public viewing in a single book. 

Why use the role system for this? It adds not another mechanism into the authentication system, but builds on the existing one.

It also allows the removal of the public-viewing setting, which currently also acts as a second authorization information source. With an unauthenticated role it just means view for the unauthenticated user role and could be managed from the role settings page together with all other authorization settings.

**Comment by ssddanbrown** [comment]
Hi @squiddle, Thanks for the suggestion. This should be fairly simple since that's exactly how the public permissions are currently handled! The system just hides the public role from any view.

If you view the `roles` table in your database you'll see a public role. Changing the `hidden` value from 1 to 0 will make it show up. Things do get funky when trying to edit as a public member though since they're not technically a user.

**Comment by riorii** [comment]
Hey @ssddanbrown , any idea if this enhancement is gonna be on the next release?

**Comment by ssddanbrown** [comment]
@riorii Yes, it will be. Although next release may not be for a small while.
