### ISSUE TITLE
Bookstack Table Linebreaks are messed up...

### ISSUE THREAD

**Issue by fredericmohr** [ssddanbrown/BookStack#142]
I think it's great that bookstack supports tables, both in markdown and in the WYSIWYG-editor. Unfortunately, the automatic linebreaks in those tables make them near unusable.

![screenshot_20160708_121340](https://cloud.githubusercontent.com/assets/5955966/16684500/aab3434a-4505-11e6-9b99-bee63324660c.png)

While it is possible to force linebreaks with `<br>`, that makes it hard to get properly formatted tables across different screen sizes. (notebooks, desktops, mobile?)

I think it would be sufficient if bookstack where to put linebreaks between words not characters.

**Comment by ssddanbrown** [comment]
Hi @fredericmohr,

Unfortunately I have found this surprisingly tricky to fix, at least in a way that pleases all situations.
I enforced a high amount of breaking as long strings with no spaces, such as long urls, would push the table way out of the page.

The current styling works fine in chrome, due to support for `word-break: break-all;` which firefox does not support. I would like to find a fix to suit all at some point but for now, If you BookStack instance is used primarily by Firefox users, you can put the following in the 'Custom HTML head content' setting:

```
<style>
.page-content table {
    word-break: normal;
}
</style>
```

**Comment by fredericmohr** [comment]
I'm actually not sure if the users use it primarily in firefox. I just noticed it and thought it might be worth mentioning. It's nothing that would keep us from using BS (which is an odd shortcut for BookStack) 

I assume the code you suggested would break things for Chrome? In that case, I'd rather wait (as long as it takes) for a fix in either BookStack or FF.

Anyway, thanks for a great tool!

**Comment by ssddanbrown** [comment]
As of v0.12.1 words are not slice across lines in firefox. I thought about this and concluded the inconsistency and chopped words were more of an issue than long words pushing out the tables, Especially since that's in the user's control whereas the line breaking is not. I will now close this issue.

Thanks again @fredericmohr for pointing this issue out.

**Comment by fredericmohr** [comment]
Thanks, I'll try it out as soon as I find the time :)
