### ISSUE TITLE
BUG: Unable to open book when name is "."

### ISSUE THREAD

**Issue by riorii** [ssddanbrown/BookStack#156]
When you create a book named "." (only the dot), it's impossible to open it or erase it.

Just reporting, nothing serious!

Regards.

**Comment by ssddanbrown** [comment]
@riorii Thanks for letting me know about this one. It also affected chapters & pages. It should now be fixed as of v0.11.1.

If you need to fix books/chapters/pages that have been made inaccessible due to this bug look in the database (On the books/chapters/pages tables) for lines with a `name` matching your book/chapter/page name and where `slug` is empty.  Set the `slug` field to any string (Keep it unique though) and you'll be able to access them again.
