### ISSUE TITLE
500 Internal Error

### ISSUE THREAD

**Issue by nowke** [ssddanbrown/BookStack#168]
I have installed according to the Docs.

When I access the domain (through IP), I am redirected to `/login` and getting `500 Server Error`. I set the debug to `True` but no `laravel.log` is generated. 

After inspecting `/opt/lampp/logs/php_error_log`, it's the problem in opening `laravel.log` (Permission Error, attached `php_error_log.txt`)

Permission for `BookStack` (which is in `/home/ubuntu/BookStack`)
```
drwxr-xr-x 12 ubuntu ubuntu 4096 Aug 21 09:31 BookStack
```

File **`/opt/lampp/etc/httpd.conf`**
```
  DocumentRoot "/home/ubuntu/BookStack/public"
  <Directory "/home/Ubuntu/BookStack">
     Options Indexes FollowSymLinks ExecCGI Includes
     AllowOverride All
     order allow,deny
     Require all granted
     Allow from all
  </Directory>

```

[php_error_log.txt](https://github.com/ssddanbrown/BookStack/files/428774/php_error_log.txt)

**Comment by ssddanbrown** [comment]
Hi @nowke,
Do you know what user and group your lampp setup runs as? Does the webserver have write permissions for the required folders?

You need to ensure the `storage`, `bootstrap/cache`, `storage` & `public/uploads` folders are all writable by the webserver.

**Comment by nowke** [comment]
Hi,

### User and Group for lampp 
```
  <IfModule unixd_module>
   User daemon
   Group daemon
  </IfModule>
```

I tried changing the ownership of `BookStack` to `www-data` and `root`. I am unable to figure out the exact permissions to be set.

Steps I followed

* Clone `BookStack` in Home directory (`/home/ubuntu/BookStack')
* Installed **Xampp** through executable in `/opt/lampp`
* Changed the `DocumentRoot` to `/home/ubuntu/BookStack/public` in the configuration file and added whole `BookStack` directory to be accessible by the server
* Migrated the Database Successfully (MySQL)

I need to host in the root itself (currently just IP). Now how do I go about the permissions? (might be simple, I am unable to figure out)

**Comment by ssddanbrown** [comment]
@nowke From the above info it looks like you apache is running as daemon. You can try the following commands (From you BookStack install folder):

``` bash
chown -R daemon:daemon public/uploads bootstrap/cache storage
chmod -R 775 public/uploads bootstrap/cache storage
```

You may have to run with `sudo ` in front of them.

Just something to note, since it looks like you're using lampp on ubuntu, On linux you usually just install the each of the LAMPP components manually via the command line rather than using Xampp since all the components in Xampp will be available in your operating system's package manager. If you wanted to go down this route instead there are plenty of guide out there, The [digital ocean guides](https://www.digitalocean.com/community/tutorials/how-to-install-linux-apache-mysql-php-lamp-stack-on-ubuntu-16-04) are usually pretty good.

**Comment by nowke** [comment]
Hi,

Great! Thanks for the input. It worked! 

I just needed this application to be hosted separately for our documentations (hence one time installation & not much maintenance). So didn't consider installing as components.

Closing issue
