### ISSUE TITLE
PDF Export - ErrorException in ExportService.php line 56

### ISSUE THREAD

**Issue by montharon** [ssddanbrown/BookStack#171]
Exception when exporting a page as a PDF file (debuggin enabled in .env)

`ErrorException in ExportService.php line 56: file_get_contents(/mnt/sda1/www/html/docs/public//docs/uploads/images/gallery/2016-08-Aug/scaled-840-0/myimage.jpg): failed to open stream: No such file or directory`

I think that the path looks weird?! Look at the 2 slashed in the path....

Thanks,
montharon

**Comment by ssddanbrown** [comment]
Thanks @montharon for letting me know of this issue. Sorry about this, Now fixed to be in the next release.

This was due how the exporter was using the image url to find image files. This has now been changed so it's compatible with BookStack instance with 'sub-directories'.

For existing pages, during an export, you may be left with blank areas instead of images (Better than erroring out). Editing then re-saving a page should update all the links and urls to be compatible with the export component.
