### ISSUE TITLE
Gravatar image error during registration

### ISSUE THREAD

**Issue by visualcohol** [ssddanbrown/BookStack#187]
### For Bug Reports
PHP Version: PHP Version 5.6.25-1

MySQL Version: 5.5

Expected Behavior: Registration mail

Actual Behavior: We just tried to Implement the wiki at our company, and a lot of the users are getting a ErrorException in ImageService.php line 68: file_get_contents(http://www.gravatar.com/.../6110ddb06429021e19723995401e0...): failed to open stream: HTTP request failed! HTTP/1.1 503 Backend fetch failed error

The registration doesn't fail, but the confirmation mail sending does, and users are confused. Since this relies on a third party and getting a user image is not so critical, maybe this should be handled more gracefully. Thanks

**Comment by ssddanbrown** [comment]
Hi @visualcohol, Thanks for reporting this and yeah, I totally agree, This should failover gracefully.

To get around this for now you can set the `DISABLE_EXTERNAL_SERVICES` variable in the `.env` file to true so it looks like this:

```
DISABLE_EXTERNAL_SERVICES=true
```

This prevents all outbound requests to third party services.

Since the bug has a workaround and is not fully critical the fix (To gracefully fail) will be in the next feature release.

**Comment by visualcohol** [comment]
@ssddanbrown - thank you - also for the great script
