### ISSUE TITLE
Running Gulp will give Error: Cannot find module 'laravel-elixir'

### ISSUE THREAD

**Issue by UnderDogg** [ssddanbrown/BookStack#191]
Hi guys,

complete fresh install with git clone (master)
- Readme didn't say anything about running gulp, but I figured that out myself...
- Running Gulp gave error message (see bug report below)
- In the master, the package.json needs to be updated, imho, but I'm not a gulp specialist...

### For Bug Reports
PHP Version: 5.x

MySQL Version: 5.x

Expected Behavior:
Running Gulp will compile sass .css and .js files

Actual Behavior:
Error message: Error: Cannot find module 'laravel-elixir'

Solution:
Open: package.json
**Add: "laravel-elixir": "*"**

Don't forget that in the readme, it doesn't say that you need to run:
npm install
gulp
(and gulp needs to be installed of course)

**Comment by ssddanbrown** [comment]
Hi @UnderDogg, Thanks for taking the time to report this error. Are you looking to develop BookStack or just install it?

If you are just installing BookStack you simply use the release branch which does not require gulp/node/npm to be used since the final CSS/JS is bundled in.

If you are looking to develop, and are getting the error above then that's a bit strange since laravel-elixir is [a listed dependancy](https://github.com/ssddanbrown/BookStack/blob/master/package.json#L15). Just to be sure, Did you definately `npm install` before getting that error?

**Comment by ssddanbrown** [comment]
I'm going to go ahead and close this. If you're still having issues just respond to the above and this can be re-opened.

**Comment by cili93** [comment]
Hey, I solved this by changing node version

I was trying `npm install laravel-elixir` but it was refusing to install properly. It was with node 10.something, but after changing node version to 8.1.3 everything was like "now we're talking", no problem whatsoever

**Comment by ssddanbrown** [comment]
Just to confirm, Bookstack does not use elixir by default. A custom webpack
based build system in used instead. See package.json scripts for the common
actions.
