### ISSUE TITLE
Sort images in page/book/chapter where they were uploaded 

### ISSUE THREAD

**Issue by THS-on** [ssddanbrown/BookStack#41]
Hello,
I uploaded nearly 300 images to BookStack. Now I have the problem that it is very hard to find new/specific images. Maybe a tag system for images is the solutuion?

THS-on

**Comment by ssddanbrown** [comment]
Hi,
Thanks for submitting this issue & sorry for my late reply. Hopefully some of the design updates to the image manager since this was posted has helped find images but I know it doesn't even start to solve the original issue. 

I'm not particularly fond of adding tags to images as it adds an extra layer of maintenance that users will have to do to keep things organised. I'm thinking if we add extra filter/search controls to the image manager so you could select options like 'Show only images in this book/chapter/page' it would keep things sane. Coupled with a search bar it should work rather well.

**Comment by ssddanbrown** [comment]
Screenshot of new controls below. This will be in the next release.

![image](https://cloud.githubusercontent.com/assets/8343178/14232790/33934efc-f9ad-11e5-9003-2c9d883e8734.png)
