### ISSUE TITLE
Possibility to create a summary

### ISSUE THREAD

**Issue by pydubreucq** [ssddanbrown/BookStack#68]
Hi,
It could be very usefull to have the possibility to create an automatic summary based on headers like on mediawiki (ex : https://meta.wikimedia.org/wiki/Help:Edit_summary the block named "Contents")
Thanks in advance and for Bookstack
Best Regards,
Pierre-Yves

**Comment by fredericmohr** [comment]
Instead of creating a new issue, I'll add my idea here.

It would be great if we could have a table of contents for pages, much like the right-hand ToC for the whole book, a ToC just for the headlines of the current page would be great on the left. It should probably scroll down with the page, since this comes especially in handy when reading long pages. See also my suggestion on the topic of additional sub-levels in #95.

**Comment by bridgeyuwa** [comment]
an example of what I think @fredericmohr said is how the page http://www.allaboutcircuits.com/textbook/ is structured

**Comment by ssddanbrown** [comment]
Simple page change summaries have now been added as of 7215392784bcbb6eca45301ed89ea04965785d27 thanks to @younes0 #140. This will be in the next release.

**Comment by ssddanbrown** [comment]
Never mind, Realised I've been a plonker and mis-read this issue.

**Comment by fredericmohr** [comment]
Any idea if/when this feature might see the light of day? :)

**Comment by mverove** [comment]
Hello,
Sorry but I can't find where/how to add a TOC in a page of book.
Maybe I've missunderstood this request but I thought it was related to TOC in book.

**Comment by ssddanbrown** [comment]
@mverove Pages get an auto-generated TOC, commonly found in the left sidebar, based upon headers.

**Comment by mverove** [comment]
@ssddanbrown Thank you !
Sorry, I thought we can include a TOC in a page to export into pdf... but you're right, it's already exported into pdf and TOC is present in the left menu.
Just have to work on pdf export layout.
