### ISSUE TITLE
Stabilize menu/content left position with this one-line fix

### ISSUE THREAD

**Issue by tpetrauskas** [ssddanbrown/BookStack#74]
Try to go to the settings page and then to some longer page ie. Book Chapter or Book Page, between page navigation. 

To fix it add this on line 7 of "BookStack/resources/assets/sass/_reset.scss"
```
overflow-y: scroll;
```

**Comment by tpetrauskas** [comment]
@ssddanbrown

**Comment by nwalke** [comment]
Can you provide a screenshot of what you're seeing?  I don't see the problem.  I did try adding that line and it started screwing up a lot of other areas that I don't think you intended.

**Comment by ssddanbrown** [comment]
I think I see the problem but I'm not really sure it's a problem that requires solving. It's basically just to force the standard vertical scrollbar to always show to prevent the width jumping about when going between pages with long and short amounts content.

Putting it on line 7 will add a scrollbar to way too many elements. Putting it only on the body (or html?) element should do the trick.

Personally I like the current browser method of the scrollbar hiding on shorter pages because it makes it obvious you can't scroll whereas a scrollbar showing up signifies scroll-ability on that page.

I'll leave this issue open as I'm open to discussion on how others feel about this one.

**Comment by mrVito** [comment]
I think that "jumping width" when page length changes is really more annoying than the fact that you will see a scroll-bar all the time, so simple `overflow-y: scroll` on `body` would be really nice. In fact, when you Really look at the scroll-bar to determine if you can scroll? :)

**Comment by ssddanbrown** [comment]
I had a play about with the permanent scroll scroll-bar and it was a nicer experience so I've added this in. The only place without it is the page editor as that uses a different flexbox-based layout and already has a scrollbar in the edit box itself.

Thanks @tpetrauskas for bringing this issue up.
