### ISSUE TITLE
Improvement: Chapter/Page Move Ability

### ISSUE THREAD

**Issue by tpetrauskas** [ssddanbrown/BookStack#86]
Sometimes I have to move a page to another chapter or from chapter straight to the book (without chapter) or even to another book. Now it's only possible to do that only by using server database management tools.

**Comment by ssddanbrown** [comment]
@tpetrauskas From what I can tell the feature you are requesting is already there? If you look at a book click the overflow menu (3 dots next to edit) then sort. When sorting you can drag chapters and books around to completely re-organise a book. On the right you can select another book to be able to move chapters and pages between books.

Let me know if I've misunderstood your request.

**Comment by tpetrauskas** [comment]
@ssddanbrown Yes, I didn't saw that. Maybe it would be helpful for the users to also have a button "Move" in single page view?

**Comment by yoginth** [comment]
there is no security while moving pages,chapters. because when one author created the book, without their permission we can move the chapters, pages etc so the book will me collapsed. Instead of that you can make as similar as pull request or they can move their pages, chapters inside their account books. Hope you will take care of this issue, THANKS.MUCH LOVE.
